**Creating numpy array and its attribute**

In [ ]:
import numpy as np
List=[1,3,5,7,9]
#Creating list named List
myArr=np.array(List)
#Creating 1-D numpy array from List
print(myArr)

#Creating 0-D array
arr0_d=np.array(42)
print(arr0_d)

#Creating 2-D array
arr_2d=np.array([[1,2,3],[4,5,6]])
print

[1 2 3 4 5]


#Homework

Creating array of 3X3 with random integer between 1 and 10 inclusive

In [ ]:
import numpy as np
#Generating random array using random of range 1 to 10;
#We are not importing random because random is of np
random_array=np.random.randint(1,11,size=(3,3))
print("Before filtering")
print(random_array)
for i in range(3):
  for j in range(3):
    if (random_array[i][j])>5.0:
      random_array[i][j]=0
print("After filtering")
print(random_array)
"""or
arr[arr>5]=0
print(arr)
"""


Before filtering
[[ 7  3  1]
 [10  7  8]
 [ 5  8 10]]
After filtering
[[0 3 1]
 [0 0 0]
 [5 0 0]]


**Creating array and using adding and using dot product.**

In [ ]:
import numpy as np
first_array=np.array([2,4,6,8])
second_array=np.array([1,3,5,7])
sum_array=first_array+second_array
dot_product=np.dot(first_array,second_array)
print(sum_array)
print(dot_product)




[ 3  7 11 15]
100


**Creating 2D array of shape 4X3 filled with ones. Then adding 1D array to 2D array using broadcasting.**


In [ ]:
import numpy as np
TwoDarr=np.ones((3,4))
OneDarr=np.array([10,20,30])
OneDarr=OneDarr.reshape(-1,1)
AddArray=TwoDarr+OneDarr
print(AddArray)


[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


**Extracting second column from 2D array and taking out mean from it**

In [ ]:
import numpy as np
#TwoDarr=(Two) (D)imension (arr)ay
TwoDarr=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(TwoDarr[1,0:])
print(mean)


5.0


Using boolean mask to select elements greater than 5 and square them and print both array

In [ ]:
import numpy as np
List=[10,20,30,40,50,60]
arr=np.array(List)

print("Before modified", arr)
for i in range(len(arr)):
  if arr[i]>30:
    arr[i]=arr[i]**2
print("After modified: ",arr)


Before modified [10 20 30 40 50 60]
After modified:  [  10   20   30 1600 2500 3600]
